import React from 'react'
import Sub from '../components/subscriptionsComponents/Sub'
import { PlanType } from '../assets/assets'
import { Metadata } from 'next';
export const metadata: Metadata = {
    title: "st george club/subscriptonpage",
    description: "Generated by create next app",
};
export default async function Subs() {

    const getAllPlans = async () => {
        try{
            const response = await fetch("https://mahinproject.runasp.net/api/Subscription/get-all-plans")
            const results = await response.json()
            if (response.ok) {
                return results
            }
        }catch(err){
            console.error(err)
        }
    }
    const plans =  await getAllPlans()
    const plansMap = plans.map((plan:PlanType) => {
        return (
            <Sub key={plan.id} plan={plan} />
        )
    })
    return (
        <main className='w-full min-h-screen bg-fixed pt-25 py-7 px-2.5 md:px-20 grid grid-cols-1 md:grid-cols-2 gap-2.5'>
            {plansMap}
        </main>
    )
}