import React from 'react'
import HeroSection from './components/home/HeroSection'
import Banner from './components/home/Banner'
import About from './components/home/About'
import Memories from './components/home/Memories'
import { Metadata } from 'next'
export const metadata: Metadata = {
    title: "st george club/homepage",
    description: "Generated by create next app",
};
export default function page() {
    return (
        <main className='w-full bg-fixed min-h-screen'>
            <HeroSection />
            <Banner />
            <About />
            <Memories/>
        </main>
    
    )
}