import React from 'react'
import RegisterLayout from '../components/registercomponents/RegisterLayout'
import { Metadata } from 'next';
export const metadata: Metadata = {
    title: "st george club/registerpage",
    description: "Generated by create next app",
};
export default function page() {
    return (
        <main className='pt-25 py-5  bg-fixed w-full min-h-screen px-5 md-px-20 flex items-center justify-center'>
            <RegisterLayout/>
    </main>
)
}
