import React from 'react'
import DashboardContent from '../components/dashboradComponents/DashboardContent'
import DashboardMembers from '../components/dashboradComponents/DashboardMembers'
import DashboardSubs from '../components/dashboradComponents/DashboardSubs'
import { getAllPlans, getAllUsers } from "../assets/Apis"
import { Metadata } from 'next';
export const metadata: Metadata = {
    title: "st george club/dashboardpage",
    description: "Generated by create next app",
};
export default async function page() {
  const allUsers = await  getAllUsers()
  const allPlans = await getAllPlans()
  return (
    <main className='min-h-screen w-full pt-25 py-5 px-5 md:px-20'>
      <DashboardContent  users={allUsers} plans={allPlans} />
      <section className='mt-3  bg-fixed grid grid-cols-1 md:grid-cols-2  gap-2.5 items-start'>
        <DashboardMembers users={allUsers} />
        <DashboardSubs plans={allPlans}/>
      </section>
    </main>
  )
}
