import React from 'react';
import ProfileInputs from "../../components/profileViewComponents/ProfileInputs"
import ProfileData from '@/app/components/profileViewComponents/ProfileData';
import { Metadata } from 'next';
export const metadata: Metadata = {
    title: "st george club/viewprofilepage",
    description: "Generated by create next app",
};
export default async function Page({ params }:{params:Promise<{id:string}>} ) {
    const { id } = await params;
    const getUser = async () => {
        try{
        const response = await fetch(`https://mahinproject.runasp.net/api/User/get-user/${id}`)
            const result = await response.json()
            return result
        
        }catch(err){
            console.error(err)
        }
    }
    const currentProfile =  await getUser()
    if(!currentProfile){
        return <h4>profile not found</h4>
    }
    return (
        <main className='pt-25 w-full min-h-screen bg-fixed py-5 px-5 md:px-20'>
            <ProfileInputs  member={currentProfile} />
            <ProfileData  />
        </main>
    )
}
